/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * catch 이벤트 응모 이력 데이터 (user)
 */
export interface CatchEventCheckUserDataItem {
  /** 응모 시간 */
  seconds?: number;
}
