/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * Catch 이벤트 응모 저장 요청 DTO
 */
export interface CatchMiniGameEntryCreateRequest {
  adid?: string;
  idfa?: string;
  /** @minLength 1 */
  platform: string;
  /** @minLength 1 */
  clickKey: string;
  /** @minLength 1 */
  userId: string;
  seconds: number;
}
