/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * catch 이벤트 응모 조건 데이터 (system)
 */
export interface CatchEventCheckSystemDataItem {
  /** 응모 시도 횟수 */
  attempt?: number;
  /** 응모 시간 */
  seconds?: number;
}
