/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {CatchEventCheckSystemDataItem} from './catchEventCheckSystemDataItem';
import type {CatchEventCheckUserDataItem} from './catchEventCheckUserDataItem';
import type {CatchEventCheckResponseResultCode} from './catchEventCheckResponseResultCode';

/**
 * catch 이벤트 응모 가능 여부 확인 응답 Response
 */
export interface CatchEventCheckResponse {
  /** 이벤트 응모 조건 */
  system: CatchEventCheckSystemDataItem;
  /** 이벤트 응모 이력 */
  user: CatchEventCheckUserDataItem[];
  /** 이벤트 응모 성공 여부 */
  isWin: boolean;
  resultCode?: CatchEventCheckResponseResultCode;
  resultMessage?: string;
}
