/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 문의 종류 (POINT_INQUIRY, AD_PARTICIPATION, SERVICE_ISSUE, OTHER)
 */
export type CSRequestInquireType =
  (typeof CSRequestInquireType)[keyof typeof CSRequestInquireType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CSRequestInquireType = {
  POINT_INQUIRY: 'POINT_INQUIRY',
  AD_PARTICIPATION: 'AD_PARTICIPATION',
  SERVICE_ISSUE: 'SERVICE_ISSUE',
  OTHER: 'OTHER',
} as const;
