/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {CSRequestInquireType} from './cSRequestInquireType';

/**
 * 사용자 CS 요청
 */
export interface CSRequest {
  /** 앱 ID */
  appId: string;
  /** 클릭 키 */
  clickKey: string;
  /** 매체에서 발급한 사용자 ID */
  userId?: string;
  /** 디바이스 플랫폼 (android, ios, web, etc) */
  platform?: string;
  /** 광고 ID (android 전용) */
  adid?: string;
  /** IDFA (ios 전용) */
  idfa?: string;
  /** 문의 내용 */
  question: string;
  /** 이메일 주소 */
  email: string;
  /** 문의 종류 (POINT_INQUIRY, AD_PARTICIPATION, SERVICE_ISSUE, OTHER) */
  inquireType: CSRequestInquireType;
  /** 첨부파일 */
  files: Blob[];
}
