/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * draw 이벤트에만 필요한 필드
 */
export type DrawEventCheckResponseDataItemShape =
  (typeof DrawEventCheckResponseDataItemShape)[keyof typeof DrawEventCheckResponseDataItemShape];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DrawEventCheckResponseDataItemShape = {
  CIRCLE: 'CIRCLE',
  RECTANGLE: 'RECTANGLE',
  TRIANGLE: 'TRIANGLE',
  RHOMBUS: 'RHOMBUS',
  PENTAGON: 'PENTAGON',
} as const;
