/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * draw 이벤트에만 필요한 필드
 */
export type DrawEventCheckSystemDataItemShape =
  (typeof DrawEventCheckSystemDataItemShape)[keyof typeof DrawEventCheckSystemDataItemShape];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DrawEventCheckSystemDataItemShape = {
  CIRCLE: 'CIRCLE',
  SQUARE: 'SQUARE',
  TRIANGLE: 'TRIANGLE',
  RHOMBUS: 'RHOMBUS',
  PENTAGON: 'PENTAGON',
} as const;
