/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * draw 이벤트 응모 이력 데이터 (user)
 */
export interface DrawEventCheckUserDataItem {
  /** 응모 시간 */
  seconds?: number;
  /** draw 이벤트에만 필요한 필드 */
  percent?: number;
}
