/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {DrawEventCheckSystemDataItem} from './drawEventCheckSystemDataItem';
import type {DrawEventCheckUserDataItem} from './drawEventCheckUserDataItem';
import type {DrawEventCheckResponseResultCode} from './drawEventCheckResponseResultCode';

/**
 * draw 이벤트 응모 가능 여부 확인 응답 Response
 */
export interface DrawEventCheckResponse {
  /** 이벤트 응모 조건 */
  system: DrawEventCheckSystemDataItem;
  /** 이벤트 응모 이력 */
  user: DrawEventCheckUserDataItem[];
  /** 이벤트 응모 성공 여부 */
  isWin: boolean;
  resultCode?: DrawEventCheckResponseResultCode;
  resultMessage?: string;
}
