/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {EmptyResponseResultCode} from './emptyResponseResultCode';

/**
 * 빈 data Response
 */
export interface EmptyResponse {
  /** 결과 코드: HTTP 상태 코드 */
  resultCode?: EmptyResponseResultCode;
  /** 결과 메시지 */
  resultMessage?: string;
}
