/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 이벤트 아이템 정보
 */
export interface EventItemsVO {
  /** 광고 고유 번호 */
  cmp_idx?: string;
  /** 광고 이름 */
  cmp_name?: string;
  /** 이벤트 아이콘 URL */
  icon_img?: string;
  /** 설명 */
  cmp_summary?: string;
  /** 간략한 설명 */
  cmp_condition?: string;
  /** 이벤트 리워드 가격 */
  reward_price?: number;
  /** 랜딩 URL */
  landing_url?: string;
}
