/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventAdPlacementInfo} from './eventAdPlacementInfo';

/**
 * 이벤트 광고 지면 정보 Response Data
 */
export interface EventAdPlacementInfoResponseData {
  intro: EventAdPlacementInfo;
  result: EventAdPlacementInfo;
}
