/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventListResponseData} from './eventListResponseData';
import type {EventListResponseResultCode} from './eventListResponseResultCode';

/**
 * 이벤트 목록 응답 Response
 */
export interface EventListResponse {
  data?: EventListResponseData;
  resultCode?: EventListResponseResultCode;
  resultMessage?: string;
}
