/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventAdPlacementInfoItems} from './eventAdPlacementInfoItems';

export interface EventAdPlacementInfo {
  isNoAdPass: boolean;
  info: EventAdPlacementInfoItems[];
}
