/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventAdPlacementInfoResponseData} from './eventAdPlacementInfoResponseData';
import type {EventAdPlacementInfoResponseResultCode} from './eventAdPlacementInfoResponseResultCode';

/**
 * 이벤트 광고 지면 정보 응답 Response
 */
export interface EventAdPlacementInfoResponse {
  data: EventAdPlacementInfoResponseData;
  resultCode?: EventAdPlacementInfoResponseResultCode;
  resultMessage?: string;
}
