/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventItemsVO} from './eventItemsVO';

/**
 * 이벤트 목록 VO
 */
export interface EventListVO {
  /** 이벤트 갯수 */
  total: number;
  /** 이벤트 아이템 정보 */
  items: EventItemsVO[];
}
