/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {EventAdPlacementInfoItemsAdOrderType} from './eventAdPlacementInfoItemsAdOrderType';
import type {EventAdPlacementInfoItemsAndroid} from './eventAdPlacementInfoItemsAndroid';
import type {EventAdPlacementInfoItemsIos} from './eventAdPlacementInfoItemsIos';

export interface EventAdPlacementInfoItems {
  adOrderType?: EventAdPlacementInfoItemsAdOrderType;
  android?: EventAdPlacementInfoItemsAndroid;
  ios?: EventAdPlacementInfoItemsIos;
  sort: number;
}
