/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {AdPopcornAdConfig} from './adPopcornAdConfig';
import type {DawinAdConfig} from './dawinAdConfig';
import type {GoogleAdConfig} from './googleAdConfig';
import type {MezzoAdConfig} from './mezzoAdConfig';

export type EventAdPlacementInfoItemsAndroid =
  | AdPopcornAdConfig
  | DawinAdConfig
  | GoogleAdConfig
  | MezzoAdConfig;
