/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {FindEventCheckSystemDataItem} from './findEventCheckSystemDataItem';
import type {FindEventCheckUserDataItem} from './findEventCheckUserDataItem';
import type {FindEventCheckResponseResultCode} from './findEventCheckResponseResultCode';

/**
 * find 이벤트 응모 가능 여부 확인 응답 Response
 */
export interface FindEventCheckResponse {
  /** 이벤트 응모 조건 */
  system: FindEventCheckSystemDataItem;
  /** 이벤트 응모 이력 */
  user: FindEventCheckUserDataItem[];
  /** 이벤트 응모 성공 여부 */
  isWin: boolean;
  resultCode?: FindEventCheckResponseResultCode;
  resultMessage?: string;
}
