/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {AdProviderConfiguration} from './adProviderConfiguration';
import type {GoogleAdConfigAllOf} from './googleAdConfigAllOf';

export type GoogleAdConfig = AdProviderConfiguration &
  GoogleAdConfigAllOf &
  Required<
    Pick<AdProviderConfiguration & GoogleAdConfigAllOf, 'adUnitPath' | 'name'>
  >;
