/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {ResponseVOResultCode} from './responseVOResultCode';
import type {ResponseVOData} from './responseVOData';

/**
 * 응답 결과 VO
 */
export interface ResponseVO {
  /** 결과 코드: HTTP 상태 코드 */
  resultCode?: ResponseVOResultCode;
  /** 결과 메시지 */
  resultMessage?: string;
  /** 응답 데이터 */
  data?: ResponseVOData;
}
