/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import type {RouletteEventCheckSystemDataItem} from './rouletteEventCheckSystemDataItem';
import type {RouletteEventCheckUserDataItem} from './rouletteEventCheckUserDataItem';
import type {RouletteEventCheckResponseResultCode} from './rouletteEventCheckResponseResultCode';

/**
 * roulette 이벤트 응모 가능 여부 확인 응답 Response
 */
export interface RouletteEventCheckResponse {
  /** 이벤트 응모 조건 */
  system: RouletteEventCheckSystemDataItem;
  /** 이벤트 응모 이력 */
  user: RouletteEventCheckUserDataItem[];
  /** 이벤트 응모 성공 여부 */
  isWin: boolean;
  resultCode?: RouletteEventCheckResponseResultCode;
  resultMessage?: string;
}
