/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * Roulette 이벤트 응모 저장 요청 DTO
 */
export interface RouletteMiniGameEntryCreateRequest {
  adid?: string;
  idfa?: string;
  /** @minLength 1 */
  platform: string;
  /** @minLength 1 */
  clickKey: string;
  /** @minLength 1 */
  userId: string;
  /** 이벤트 응모 데이터: roulette rate */
  rate: number;
}
