/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * 핀플로우 프로모션: API
 * 핀플로우 프로모션: API 문서
 * OpenAPI spec version: 1.0
 */
import {z as zod} from 'zod';

/**
 * @summary 앱 별 이벤트 중복 참여 체크
 */
export const checkDuplicateEntryParams = zod.object({
  appId: zod.string(),
});

export const checkDuplicateEntryQueryParams = zod.object({
  pId: zod.string(),
  adid: zod.string().optional(),
  idfa: zod.string().optional(),
  userId: zod.string(),
});

/**
 * 광고 매체사 지면에 미니게임 목록 제공을 위한 API
 * @summary 광고 매체 별 이벤트 목록 조회
 */
export const getEventListParams = zod.object({
  appId: zod.string(),
});
